### ISSUE TITLE
Unmanaged style layer disappears when sorting

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#587] opened 2024-01-16 16:10 UTC
1. Feature is selected
2. Layer is dragged below other layer
3. Feature does not appear selected anymore

In fact, also the hover style is gone.

[Peek 2024-01-16 17-09.webm](https://github.com/EOX-A/EOxElements/assets/8948865/180175b2-0dbe-45be-95c1-cc76ed49fdcf)

**Comment by silvester-pari** [comment] 2024-01-17 06:25
I feel like this is a general issue with reordering if we have temporary layers. It would be nice to see if it happens with "vanilla" OL manipulation in order to make sure it's not a bug in layercontrol.

**Comment by silvester-pari** [comment] 2024-01-17 07:19
I managed to reproduce this issue in a codesandbox: https://codesandbox.io/p/sandbox/temporary-layers-2ccxlx
The issue is not connected to the layercontrol, so I'll go ahead and remove the layercontrol label.

**Comment by silvester-pari** [comment] 2024-02-13 09:33
@RobertOrthofer I don't get why the [`removeAt`](https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html#removeAt) and [`insertAt`](https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html#insertAt) functions should be a non-API-way of removing/adding layers from the viewpoint of ol?  :thinking: How else could we do the layer sorting in vanilla ol? I am aware of `map.removeLayer`, but it doesn't work in groups, and how to re-add the layer after sorting is done?

Having said that, I can't reproduce the sandbox code issue either in `1.2.0`, it seems that the interaction is not removed together with the layer any more (even with `map.removeLayer`, and even when using the eox-map `layers` property), so hover etc. still there even if the layer is gone. In `1.1.0` it removes the layer + interaction, but it does not come back after re-inserting the layer.

**Comment by silvester-pari** [comment] 2024-07-04 08:15
Fixed in #1078

**Closed by silvester-pari** 2024-07-04 08:15 UTC
Labels: bug, map
