### ISSUE TITLE
Push of a new layer into a LayerGroup on top most level does not trigger a refresh of DOM

### ISSUE THREAD

**Issue by lubojr** [EOX-A/EOxElements#242] opened 2023-09-14 11:12 UTC
The layer is correctly shown when the UI panel containing the layer switcher is hidden and shown again, but the render is not triggered by itself on push to the collection.

Observed on latest version 0.6.5

**Comment by silvester-pari** [comment] 2023-09-14 11:55
We had this issue but couldn't reproduce it in a test: https://github.com/EOX-A/EOxElements/issues/211
Closing this issue as duplicate and reopening that one.

**Closed by silvester-pari** 2023-09-14 11:55 UTC
Labels: bug, layercontrol
